-- ============================================================
-- AR dialogue_order (재배치 규칙 반영)
-- Generated by generate_dialogue_order.py
-- 
-- 전제: items.dialogue_order 컬럼 존재 (seed_alter_v15.sql 먼저 실행)
-- ============================================================

-- L2: 2 dialogues
update public.items set dialogue_order =   1 where id like 'ar:sent:l2_d16_%';
update public.items set dialogue_order =   2 where id like 'ar:sent:l2_d17_%';

-- L3: 2 dialogues
update public.items set dialogue_order =   1 where id like 'ar:sent:l3_d16_%';
update public.items set dialogue_order =   2 where id like 'ar:sent:l3_d17_%';

-- L4: 2 dialogues
update public.items set dialogue_order =   1 where id like 'ar:sent:l4_d16_%';
update public.items set dialogue_order =   2 where id like 'ar:sent:l4_d17_%';

-- L6: 2 dialogues
update public.items set dialogue_order =   1 where id like 'ar:sent:l6_d16_%';
update public.items set dialogue_order =   2 where id like 'ar:sent:l6_d17_%';
